language: python
sudo: false
python:
- 2.7

addons:
  apt:
    packages:
    - python-lxml
    - python-pip

install:
- pip install xml2rfc

script: 
- make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
